### ISSUE TITLE
application初始化部分机型报null指针

### ISSUE THREAD

**Issue by xiaoyao5544** [easemob/sdkdemoapp3.0_android#284]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:383)
	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:378)
	# at com.hyphenate.chat.EMSessionManager.getLastLoginUser(Unknown Source)
	at com.hyphenate.chat.EMClient.init(Unknown Source)
	at com.hyphenate.chat.ChatClient.init(ChatClient.java:147)

**Comment by checkming** [comment]
哥们 ，你解决了吗
